// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResilienciaNorte.Repository;

#nullable disable

namespace ResilienciaNorte.Repository.Migrations
{
    [DbContext(typeof(ResilienciaDbContext))]
    [Migration("20260929065102_MigracionInicialCompleta")]
    partial class MigracionInicialCompleta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResilienciaNorte.Domain.AuditoriaSistema", b =>
                {
                    b.Property<long>("AuditoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditoriaId"));

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaHoraUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RolUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuditoriaId");

                    b.ToTable("AuditoriaSistema");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.DetalleOrden", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("CantidadEntregada")
                        .HasColumnType("int");

                    b.Property<int>("CantidadSolicitada")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int");

                    b.Property<int>("RecursoId")
                        .HasColumnType("int");

                    b.HasKey("DetalleId");

                    b.HasIndex("OrdenId");

                    b.HasIndex("RecursoId");

                    b.ToTable("DetallesOrden");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.Distrito", b =>
                {
                    b.Property<int>("DistritoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistritoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("NivelRiesgo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UbicacionCOEL")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("DistritoId");

                    b.ToTable("Distritos");

                    b.HasData(
                        new
                        {
                            DistritoId = 1,
                            Activo = true,
                            NivelRiesgo = "Alto",
                            Nombre = "El Porvenir",
                            UbicacionCOEL = "Av. Sánchez Carrión 1200"
                        },
                        new
                        {
                            DistritoId = 2,
                            Activo = true,
                            NivelRiesgo = "Alto",
                            Nombre = "Florencia de Mora",
                            UbicacionCOEL = "Calle 20 de Setiembre"
                        },
                        new
                        {
                            DistritoId = 3,
                            Activo = true,
                            NivelRiesgo = "Medio",
                            Nombre = "La Esperanza",
                            UbicacionCOEL = "Plaza de Armas La Esperanza"
                        },
                        new
                        {
                            DistritoId = 4,
                            Activo = true,
                            NivelRiesgo = "Medio",
                            Nombre = "Huanchaco",
                            UbicacionCOEL = "Av. Víctor Larco Herrera"
                        },
                        new
                        {
                            DistritoId = 5,
                            Activo = true,
                            NivelRiesgo = "Alto",
                            Nombre = "Víctor Larco Herrera",
                            UbicacionCOEL = "Buenos Aires"
                        },
                        new
                        {
                            DistritoId = 6,
                            Activo = true,
                            NivelRiesgo = "Bajo",
                            Nombre = "Trujillo Centro",
                            UbicacionCOEL = "COEP - Palacio Municipal"
                        });
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.IncidenteEmergencia", b =>
                {
                    b.Property<int>("IncidenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidenteId"));

                    b.Property<string>("CodigoIncidente")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DireccionReferencia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DistritoId")
                        .HasColumnType("int");

                    b.Property<int?>("DistritoId1")
                        .HasColumnType("int");

                    b.Property<string>("DniCiudadano")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Reportado");

                    b.Property<int>("FamiliasAfectadas")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCiudadano")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SectorCritico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Severidad")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Moderado");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IncidenteId");

                    b.HasIndex("CodigoIncidente")
                        .IsUnique();

                    b.HasIndex("DistritoId");

                    b.HasIndex("DistritoId1");

                    b.ToTable("IncidentesEmergencia");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.MovimientoAlmacen", b =>
                {
                    b.Property<int>("MovimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovimientoId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("ConceptoMovimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DistritoId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentoReferencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntidadOrigenDestino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecursoId")
                        .HasColumnType("int");

                    b.Property<int>("StockAnterior")
                        .HasColumnType("int");

                    b.Property<int>("StockPosterior")
                        .HasColumnType("int");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UsuarioResponsableId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovimientoId");

                    b.HasIndex("DistritoId");

                    b.HasIndex("RecursoId");

                    b.ToTable("MovimientosAlmacen");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.OrdenAtencion", b =>
                {
                    b.Property<int>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdenId"));

                    b.Property<string>("CodigoOrden")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Aprobada");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<int>("IncidenteId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioAnalistaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioCoordinadorId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrdenId");

                    b.HasIndex("CodigoOrden")
                        .IsUnique();

                    b.HasIndex("IncidenteId")
                        .IsUnique();

                    b.ToTable("OrdenesAtencion");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.RecursoAlmacen", b =>
                {
                    b.Property<int>("RecursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecursoId"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodigoBAH")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DistritoId")
                        .HasColumnType("int");

                    b.Property<int?>("DistritoId1")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StockDisponible")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RecursoId");

                    b.HasIndex("CodigoBAH")
                        .IsUnique();

                    b.HasIndex("DistritoId");

                    b.HasIndex("DistritoId1");

                    b.ToTable("RecursosAlmacen");

                    b.HasData(
                        new
                        {
                            RecursoId = 1,
                            Categoria = "Defensa Ribereña",
                            CodigoBAH = "BAH-001",
                            DistritoId = 1,
                            Nombre = "Sacos terreros de polipropileno",
                            StockDisponible = 15000,
                            StockMinimo = 500,
                            UnidadMedida = "Unidades"
                        },
                        new
                        {
                            RecursoId = 2,
                            Categoria = "Techo",
                            CodigoBAH = "BAH-002",
                            DistritoId = 1,
                            Nombre = "Bobinas de plástico impermeable 6x50m",
                            StockDisponible = 300,
                            StockMinimo = 20,
                            UnidadMedida = "Rollos"
                        },
                        new
                        {
                            RecursoId = 3,
                            Categoria = "Equipamiento",
                            CodigoBAH = "BAH-003",
                            DistritoId = 1,
                            Nombre = "Motobomba de achique autocebante 4\"",
                            StockDisponible = 15,
                            StockMinimo = 3,
                            UnidadMedida = "Equipos"
                        },
                        new
                        {
                            RecursoId = 4,
                            Categoria = "Techo",
                            CodigoBAH = "BAH-004",
                            DistritoId = 1,
                            Nombre = "Calaminas galvanizadas 1.83x0.83m",
                            StockDisponible = 5000,
                            StockMinimo = 200,
                            UnidadMedida = "Planchas"
                        },
                        new
                        {
                            RecursoId = 5,
                            Categoria = "Alimentos",
                            CodigoBAH = "BAH-005",
                            DistritoId = 1,
                            Nombre = "Kit de víveres no perecibles (ración 3 días)",
                            StockDisponible = 2000,
                            StockMinimo = 100,
                            UnidadMedida = "Kits"
                        });
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.SolicitudReabastecimiento", b =>
                {
                    b.Property<int>("SolicitudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolicitudId"));

                    b.Property<int>("CantidadSolicitada")
                        .HasColumnType("int");

                    b.Property<string>("CodigoSolicitud")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("DistritoOrigenId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime?>("FechaAtencion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<string>("Justificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelDestino")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RecursoId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAprobadorId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SolicitudId");

                    b.HasIndex("CodigoSolicitud")
                        .IsUnique();

                    b.HasIndex("DistritoOrigenId");

                    b.HasIndex("RecursoId");

                    b.ToTable("SolicitudesReabastecimiento");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.VerificacionOtpCiudadano", b =>
                {
                    b.Property<int>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OtpId"));

                    b.Property<string>("CodigoIncidente")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DniCiudadano")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FueUtilizado")
                        .HasColumnType("bit");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("int");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("OtpId");

                    b.ToTable("VerificacionesOtpCiudadano");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.DetalleOrden", b =>
                {
                    b.HasOne("ResilienciaNorte.Domain.OrdenAtencion", "OrdenAtencion")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResilienciaNorte.Domain.RecursoAlmacen", "Recurso")
                        .WithMany()
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenAtencion");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.IncidenteEmergencia", b =>
                {
                    b.HasOne("ResilienciaNorte.Domain.Distrito", "Distrito")
                        .WithMany()
                        .HasForeignKey("DistritoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResilienciaNorte.Domain.Distrito", null)
                        .WithMany("Incidentes")
                        .HasForeignKey("DistritoId1");

                    b.Navigation("Distrito");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.MovimientoAlmacen", b =>
                {
                    b.HasOne("ResilienciaNorte.Domain.Distrito", "Distrito")
                        .WithMany()
                        .HasForeignKey("DistritoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResilienciaNorte.Domain.RecursoAlmacen", "Recurso")
                        .WithMany()
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Distrito");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.OrdenAtencion", b =>
                {
                    b.HasOne("ResilienciaNorte.Domain.IncidenteEmergencia", "Incidente")
                        .WithOne()
                        .HasForeignKey("ResilienciaNorte.Domain.OrdenAtencion", "IncidenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Incidente");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.RecursoAlmacen", b =>
                {
                    b.HasOne("ResilienciaNorte.Domain.Distrito", "Distrito")
                        .WithMany()
                        .HasForeignKey("DistritoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResilienciaNorte.Domain.Distrito", null)
                        .WithMany("Recursos")
                        .HasForeignKey("DistritoId1");

                    b.Navigation("Distrito");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.SolicitudReabastecimiento", b =>
                {
                    b.HasOne("ResilienciaNorte.Domain.Distrito", "DistritoOrigen")
                        .WithMany()
                        .HasForeignKey("DistritoOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResilienciaNorte.Domain.RecursoAlmacen", "Recurso")
                        .WithMany()
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DistritoOrigen");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.Distrito", b =>
                {
                    b.Navigation("Incidentes");

                    b.Navigation("Recursos");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.OrdenAtencion", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
