// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResilienciaNorte.Repository;

#nullable disable

namespace ResilienciaNorte.Repository.Migrations
{
    [DbContext(typeof(ResilienciaDbContext))]
    [Migration("20261002051355_MigracionInicialConIdentity")]
    partial class MigracionInicialConIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.AuditoriaSistema", b =>
                {
                    b.Property<long>("AuditoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditoriaId"));

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("FechaHoraUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpCliente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RolUsuario")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuditoriaId");

                    b.ToTable("AuditoriaSistema");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.DetalleOrden", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleId"));

                    b.Property<int>("CantidadEntregada")
                        .HasColumnType("int");

                    b.Property<int>("CantidadSolicitada")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrdenId")
                        .HasColumnType("int");

                    b.Property<int>("RecursoId")
                        .HasColumnType("int");

                    b.HasKey("DetalleId");

                    b.HasIndex("OrdenId");

                    b.HasIndex("RecursoId");

                    b.ToTable("DetallesOrden");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.Distrito", b =>
                {
                    b.Property<int>("DistritoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistritoId"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("NivelRiesgo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("UbicacionCOEL")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("DistritoId");

                    b.ToTable("Distritos");

                    b.HasData(
                        new
                        {
                            DistritoId = 1,
                            Activo = true,
                            NivelRiesgo = "Alto",
                            Nombre = "El Porvenir",
                            UbicacionCOEL = "Av. Sánchez Carrión 1200"
                        },
                        new
                        {
                            DistritoId = 2,
                            Activo = true,
                            NivelRiesgo = "Alto",
                            Nombre = "Florencia de Mora",
                            UbicacionCOEL = "Calle 20 de Setiembre"
                        },
                        new
                        {
                            DistritoId = 3,
                            Activo = true,
                            NivelRiesgo = "Medio",
                            Nombre = "Huanchaco",
                            UbicacionCOEL = "Av. Víctor Larco Herrera"
                        },
                        new
                        {
                            DistritoId = 4,
                            Activo = true,
                            NivelRiesgo = "Medio",
                            Nombre = "La Esperanza",
                            UbicacionCOEL = "Plaza de Armas La Esperanza"
                        },
                        new
                        {
                            DistritoId = 5,
                            Activo = true,
                            NivelRiesgo = "Alto",
                            Nombre = "Laredo",
                            UbicacionCOEL = "Riberas cuenca Río Moche"
                        },
                        new
                        {
                            DistritoId = 6,
                            Activo = true,
                            NivelRiesgo = "Medio",
                            Nombre = "Moche",
                            UbicacionCOEL = "Campiña de Moche"
                        },
                        new
                        {
                            DistritoId = 7,
                            Activo = true,
                            NivelRiesgo = "Alto",
                            Nombre = "Poroto",
                            UbicacionCOEL = "Sector Quebradas Altas"
                        },
                        new
                        {
                            DistritoId = 8,
                            Activo = true,
                            NivelRiesgo = "Bajo",
                            Nombre = "Salaverry",
                            UbicacionCOEL = "Zona Portuaria"
                        },
                        new
                        {
                            DistritoId = 9,
                            Activo = true,
                            NivelRiesgo = "Alto",
                            Nombre = "Simbal",
                            UbicacionCOEL = "Cuenca Alta Río Moche"
                        },
                        new
                        {
                            DistritoId = 10,
                            Activo = true,
                            NivelRiesgo = "Bajo",
                            Nombre = "Trujillo",
                            UbicacionCOEL = "COEP - Palacio Municipal"
                        },
                        new
                        {
                            DistritoId = 11,
                            Activo = true,
                            NivelRiesgo = "Alto",
                            Nombre = "Víctor Larco Herrera",
                            UbicacionCOEL = "Buenos Aires Sur"
                        });
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.IncidenteEmergencia", b =>
                {
                    b.Property<int>("IncidenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidenteId"));

                    b.Property<string>("CodigoIncidente")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DireccionReferencia")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DistritoId")
                        .HasColumnType("int");

                    b.Property<string>("DniCiudadano")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Reportado");

                    b.Property<int>("FamiliasAfectadas")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCiudadano")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SectorCritico")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Severidad")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Moderado");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IncidenteId");

                    b.HasIndex("CodigoIncidente")
                        .IsUnique();

                    b.HasIndex("DistritoId");

                    b.ToTable("IncidentesEmergencia");

                    b.HasData(
                        new
                        {
                            IncidenteId = 1,
                            CodigoIncidente = "ALT-2026-0001",
                            Descripcion = "Drenaje pluvial colapsado por barro acumulado tras lluvias en la parte alta. Afectación a viviendas contiguas.",
                            DireccionReferencia = "Av. Sánchez Carrión cuadra 12, El Porvenir",
                            DistritoId = 1,
                            DniCiudadano = "71234567",
                            Estado = "Constatado",
                            FamiliasAfectadas = 18,
                            FechaRegistro = new DateTime(2026, 9, 18, 14, 30, 0, 0, DateTimeKind.Utc),
                            NombreCiudadano = "Juan Carlos Pérez",
                            SectorCritico = "Sector Río Seco - Quebrada San Ildefonso",
                            Severidad = "Crítico",
                            Telefono = "944112233",
                            TipoEvento = "Desborde Quebrada"
                        },
                        new
                        {
                            IncidenteId = 2,
                            CodigoIncidente = "ALT-2026-0002",
                            Descripcion = "Escorrentía superficial ingresando a predios en el margen de la carretera.",
                            DireccionReferencia = "Entrada principal a El Trópico, Huanchaco",
                            DistritoId = 4,
                            DniCiudadano = "40987654",
                            Estado = "Reportado",
                            FamiliasAfectadas = 5,
                            FechaRegistro = new DateTime(2026, 9, 18, 18, 15, 0, 0, DateTimeKind.Utc),
                            NombreCiudadano = "María Elena Rojas",
                            SectorCritico = "Entrada principal a El Trópico",
                            Severidad = "Moderado",
                            Telefono = "988776655",
                            TipoEvento = "Inundación Pluvial"
                        });
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.MovimientoAlmacen", b =>
                {
                    b.Property<int>("MovimientoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovimientoId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("ConceptoMovimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DistritoId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentoReferencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntidadOrigenDestino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecursoId")
                        .HasColumnType("int");

                    b.Property<int>("StockAnterior")
                        .HasColumnType("int");

                    b.Property<int>("StockPosterior")
                        .HasColumnType("int");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UsuarioResponsableId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovimientoId");

                    b.HasIndex("DistritoId");

                    b.HasIndex("RecursoId");

                    b.ToTable("MovimientosAlmacen");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.OrdenAtencion", b =>
                {
                    b.Property<int>("OrdenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdenId"));

                    b.Property<string>("CodigoOrden")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Aprobada");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<int>("IncidenteId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioAnalistaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioCoordinadorId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrdenId");

                    b.HasIndex("CodigoOrden")
                        .IsUnique();

                    b.HasIndex("IncidenteId")
                        .IsUnique();

                    b.ToTable("OrdenesAtencion");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.RecursoAlmacen", b =>
                {
                    b.Property<int>("RecursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecursoId"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodigoBAH")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DistritoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StockDisponible")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RecursoId");

                    b.HasIndex("CodigoBAH")
                        .IsUnique();

                    b.HasIndex("DistritoId");

                    b.ToTable("RecursosAlmacen");

                    b.HasData(
                        new
                        {
                            RecursoId = 1,
                            Categoria = "Defensa Ribereña",
                            CodigoBAH = "BAH-001",
                            DistritoId = 1,
                            Nombre = "Sacos terreros de polipropileno",
                            StockDisponible = 15000,
                            StockMinimo = 500,
                            UnidadMedida = "Unidades"
                        },
                        new
                        {
                            RecursoId = 2,
                            Categoria = "Techo",
                            CodigoBAH = "BAH-002",
                            DistritoId = 1,
                            Nombre = "Bobinas de plástico impermeable 6x50m",
                            StockDisponible = 300,
                            StockMinimo = 20,
                            UnidadMedida = "Rollos"
                        },
                        new
                        {
                            RecursoId = 3,
                            Categoria = "Equipamiento",
                            CodigoBAH = "BAH-003",
                            DistritoId = 1,
                            Nombre = "Motobomba de achique autocebante 4\"",
                            StockDisponible = 15,
                            StockMinimo = 3,
                            UnidadMedida = "Equipos"
                        },
                        new
                        {
                            RecursoId = 4,
                            Categoria = "Techo",
                            CodigoBAH = "BAH-004",
                            DistritoId = 1,
                            Nombre = "Calaminas galvanizadas 1.83x0.83m",
                            StockDisponible = 5000,
                            StockMinimo = 200,
                            UnidadMedida = "Planchas"
                        },
                        new
                        {
                            RecursoId = 5,
                            Categoria = "Alimentos",
                            CodigoBAH = "BAH-005",
                            DistritoId = 1,
                            Nombre = "Kit de víveres no perecibles (ración 3 días)",
                            StockDisponible = 2000,
                            StockMinimo = 100,
                            UnidadMedida = "Kits"
                        },
                        new
                        {
                            RecursoId = 6,
                            Categoria = "Abrigo",
                            CodigoBAH = "BAH-006",
                            DistritoId = 5,
                            Nombre = "Camas plegables de lona para albergues",
                            StockDisponible = 120,
                            StockMinimo = 25,
                            UnidadMedida = "Unidades"
                        });
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.SolicitudReabastecimiento", b =>
                {
                    b.Property<int>("SolicitudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolicitudId"));

                    b.Property<int>("CantidadSolicitada")
                        .HasColumnType("int");

                    b.Property<string>("CodigoSolicitud")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("DistritoOrigenId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime?>("FechaAtencion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<string>("Justificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelDestino")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RecursoId")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioAprobadorId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SolicitudId");

                    b.HasIndex("CodigoSolicitud")
                        .IsUnique();

                    b.HasIndex("DistritoOrigenId");

                    b.HasIndex("RecursoId");

                    b.ToTable("SolicitudesReabastecimiento");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.UsuarioAplicacion", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DistritoId")
                        .HasColumnType("int");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NivelJurisdiccion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DistritoId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.VerificacionOtpCiudadano", b =>
                {
                    b.Property<int>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OtpId"));

                    b.Property<string>("CodigoIncidente")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("DniCiudadano")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FueUtilizado")
                        .HasColumnType("bit");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("int");

                    b.Property<string>("PinHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("OtpId");

                    b.ToTable("VerificacionesOtpCiudadano");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ResilienciaNorte.Domain.UsuarioAplicacion", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ResilienciaNorte.Domain.UsuarioAplicacion", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResilienciaNorte.Domain.UsuarioAplicacion", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ResilienciaNorte.Domain.UsuarioAplicacion", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.DetalleOrden", b =>
                {
                    b.HasOne("ResilienciaNorte.Domain.OrdenAtencion", "OrdenAtencion")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResilienciaNorte.Domain.RecursoAlmacen", "Recurso")
                        .WithMany()
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenAtencion");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.IncidenteEmergencia", b =>
                {
                    b.HasOne("ResilienciaNorte.Domain.Distrito", "Distrito")
                        .WithMany("Incidentes")
                        .HasForeignKey("DistritoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Distrito");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.MovimientoAlmacen", b =>
                {
                    b.HasOne("ResilienciaNorte.Domain.Distrito", "Distrito")
                        .WithMany()
                        .HasForeignKey("DistritoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResilienciaNorte.Domain.RecursoAlmacen", "Recurso")
                        .WithMany()
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Distrito");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.OrdenAtencion", b =>
                {
                    b.HasOne("ResilienciaNorte.Domain.IncidenteEmergencia", "Incidente")
                        .WithOne()
                        .HasForeignKey("ResilienciaNorte.Domain.OrdenAtencion", "IncidenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Incidente");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.RecursoAlmacen", b =>
                {
                    b.HasOne("ResilienciaNorte.Domain.Distrito", "Distrito")
                        .WithMany("Recursos")
                        .HasForeignKey("DistritoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Distrito");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.SolicitudReabastecimiento", b =>
                {
                    b.HasOne("ResilienciaNorte.Domain.Distrito", "DistritoOrigen")
                        .WithMany()
                        .HasForeignKey("DistritoOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ResilienciaNorte.Domain.RecursoAlmacen", "Recurso")
                        .WithMany()
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DistritoOrigen");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.UsuarioAplicacion", b =>
                {
                    b.HasOne("ResilienciaNorte.Domain.Distrito", "Distrito")
                        .WithMany()
                        .HasForeignKey("DistritoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Distrito");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.Distrito", b =>
                {
                    b.Navigation("Incidentes");

                    b.Navigation("Recursos");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.OrdenAtencion", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
