// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResilienciaNorte.Repository;

#nullable disable

namespace ResilienciaNorte.Repository.Migrations
{
    [DbContext(typeof(ResilienciaDbContext))]
    partial class ResilienciaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ResilienciaNorte.Domain.Distrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PoblacionEstimada")
                        .HasColumnType("int");

                    b.Property<string>("ZonaVulnerablePrincipal")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Distritos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "El Porvenir",
                            PoblacionEstimada = 195000,
                            ZonaVulnerablePrincipal = "Quebrada San Ildefonso / Río Seco"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Florencia de Mora",
                            PoblacionEstimada = 42000,
                            ZonaVulnerablePrincipal = "Sectores bajos y red troncal de desagüe"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Nombre = "La Esperanza",
                            PoblacionEstimada = 189000,
                            ZonaVulnerablePrincipal = "Parte alta / Quebrada El León"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Nombre = "Trujillo Centro Historico",
                            PoblacionEstimada = 315000,
                            ZonaVulnerablePrincipal = "Av. España y microcuenca pluvial urbana"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Nombre = "Huanchaco",
                            PoblacionEstimada = 68000,
                            ZonaVulnerablePrincipal = "El Trópico y desembocadura Quebrada El León"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Nombre = "Víctor Larco Herrera",
                            PoblacionEstimada = 65000,
                            ZonaVulnerablePrincipal = "Sector Buenos Aires Sur / Inundaciones costeras"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Nombre = "Laredo",
                            PoblacionEstimada = 37000,
                            ZonaVulnerablePrincipal = "Riberas de la cuenca del Río Moche"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Nombre = "Moche",
                            PoblacionEstimada = 38000,
                            ZonaVulnerablePrincipal = "Campiña de Moche y zonas agrícolas ribereñas"
                        });
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.IncidenteEmergencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DireccionReferencia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DistritoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("FamiliasAfectadas")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaReporte")
                        .HasColumnType("datetime2");

                    b.Property<string>("NivelSeveridad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoDesastre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("DistritoId");

                    b.ToTable("IncidentesEmergencia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Drenaje pluvial colapsado por barro acumulado tras lluvias en la parte alta. Afectación a viviendas contiguas.",
                            DireccionReferencia = "Av. Sánchez Carrión cuadra 12, El Porvenir",
                            DistritoId = 1,
                            Estado = "En Evaluación",
                            FamiliasAfectadas = 18,
                            FechaReporte = new DateTime(2026, 9, 18, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            NivelSeveridad = "Crítico",
                            TipoDesastre = "Inundación Pluvial",
                            Titulo = "Acumulación pluvial crítica en Sector Río Seco"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Escorrentía superficial ingresando a predios en el margen de la carretera.",
                            DireccionReferencia = "Entrada principal a El Trópico, Huanchaco",
                            DistritoId = 5,
                            Estado = "Pendiente",
                            FamiliasAfectadas = 5,
                            FechaReporte = new DateTime(2026, 9, 18, 18, 15, 0, 0, DateTimeKind.Unspecified),
                            NivelSeveridad = "Moderado",
                            TipoDesastre = "Inundación Pluvial",
                            Titulo = "Anegamiento de calzada principal en El Trópico"
                        });
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.RecursoAlmacen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoBAH")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("DistritoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("StockDisponible")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimoSeguridad")
                        .HasColumnType("int");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DistritoId");

                    b.ToTable("RecursosAlmacen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoBAH = "BAH-001",
                            DistritoId = 1,
                            Nombre = "Sacos terreros de polipropileno",
                            StockDisponible = 5000,
                            StockMinimoSeguridad = 1000,
                            UnidadMedida = "Unidades"
                        },
                        new
                        {
                            Id = 2,
                            CodigoBAH = "BAH-002",
                            DistritoId = 1,
                            Nombre = "Bobinas de plástico calibre pesado (200m)",
                            StockDisponible = 150,
                            StockMinimoSeguridad = 30,
                            UnidadMedida = "Rollos"
                        },
                        new
                        {
                            Id = 3,
                            CodigoBAH = "BAH-003",
                            DistritoId = 4,
                            Nombre = "Motobomba de achique autocebante 4\"",
                            StockDisponible = 8,
                            StockMinimoSeguridad = 2,
                            UnidadMedida = "Equipos"
                        },
                        new
                        {
                            Id = 4,
                            CodigoBAH = "BAH-004",
                            DistritoId = 3,
                            Nombre = "Carpas familiares de lona impermeable",
                            StockDisponible = 60,
                            StockMinimoSeguridad = 15,
                            UnidadMedida = "Unidades"
                        },
                        new
                        {
                            Id = 5,
                            CodigoBAH = "BAH-005",
                            DistritoId = 5,
                            Nombre = "Bidones de agua potable 20L",
                            StockDisponible = 400,
                            StockMinimoSeguridad = 100,
                            UnidadMedida = "Unidades"
                        },
                        new
                        {
                            Id = 6,
                            CodigoBAH = "BAH-006",
                            DistritoId = 6,
                            Nombre = "Camas plegables de lona para albergues",
                            StockDisponible = 120,
                            StockMinimoSeguridad = 25,
                            UnidadMedida = "Unidades"
                        });
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.IncidenteEmergencia", b =>
                {
                    b.HasOne("ResilienciaNorte.Domain.Distrito", "Distrito")
                        .WithMany("Incidentes")
                        .HasForeignKey("DistritoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Distrito");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.RecursoAlmacen", b =>
                {
                    b.HasOne("ResilienciaNorte.Domain.Distrito", "Distrito")
                        .WithMany("Recursos")
                        .HasForeignKey("DistritoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Distrito");
                });

            modelBuilder.Entity("ResilienciaNorte.Domain.Distrito", b =>
                {
                    b.Navigation("Incidentes");

                    b.Navigation("Recursos");
                });
#pragma warning restore 612, 618
        }
    }
}
